name: build-and-run-tests-macos
run-name: Build and run tests
on: [push]
jobs:
  do-it:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install OpenMP
        run: brew install libomp
      - name: Use cmake
        run: |
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_FLAGS="-I/opt/homebrew/opt/libomp/include" \
            -DCMAKE_CXX_FLAGS="-I/opt/homebrew/opt/libomp/include" \
            -DCMAKE_EXE_LINKER_FLAGS="-L/opt/homebrew/opt/libomp/lib -lomp" \
            -DCMAKE_SHARED_LINKER_FLAGS="-L/opt/homebrew/opt/libomp/lib -lomp"
          make -j10
      - name: Run tests
        run: |
          cd build
          ctest -j10 --rerun-failed --output-on-failure
