name: build-and-run-tests
run-name: Build and run tests
on: [push]
jobs:
  do-it:
    runs-on: ubuntu-latest
    container: gcc:13
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.28.x'
      - name: Use cmake
        run: |
          mkdir build
          cd build
          echo "CXX=g++-10" >> $GITHUB_ENV
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j10
      - name: Run tests
        run: |
          cd build
          ctest -j10
